//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид оплаты.
    /// </summary>
    // *** Start programmer edit section *** (ВидОплаты CustomAttributes)

    // *** End programmer edit section *** (ВидОплаты CustomAttributes)
    public enum ВидОплаты
    {
    }
}
